absmach/magistrala-old

pkg/sdk/go/channels.go
pkg/sdk/go/groups.go
pkg/sdk/go/things.go
pkg/sdk/go/users.go

Fix some faults found in the sdk, that don't match with what is in the service.
None
None
No
None

NOISSUE- Fix sdk

---

Makefile

The DOCKER_PROJECT variable was not being assigned correctly due to a missing closing parenthesis in the command. This has been fixed by adding the missing parenthesis.
No issue
None
No
No
N/A

NOISSUE - Fix Makefile

---

pkg/sdk/go/sdk.go

Add the checking of Permission from page metadata and adding it to the query parameters in sdk
None
None
No
No

NOISSUE - Add Permission to sdk query

---

.semaphore/semaphore.yml
README.md

This pull request fixes the branch name in the Semaphore CI config file.
There is no such issue.
N/A
N/A
N/A
N/A

NOISSUE - Fix branch name in Semaphore

---

ws/adapter_test.go

The test case was returning a wrapped error yet it was supposed to return a single error. The wrapped error was just a duplicate.
Related to #37 
None
Yes
No
N/A

NOISSUE - Fix WS Tests

---

certs/postgres/setup_test.go
certs/service_test.go

Fix tests in the `certs` package
This relates to #37 
None
Yes
No
N/A

NOISSUE - Fix Certs Tests

---

auth/mocks/service.go
users/service.go
users/service_test.go

Fix tests in users service to ensure there are no failing tests
Related to #37 
None
Yes
No
N/A

NOISSUE - Fix Users Tests

---

docker/brokers/profiles/README.md

The readme mentions 2 files when there is only one file

NOISSUE - Update error in nats documentation

---

users/postgres/clients_test.go
users/postgres/init.go

This commit adds a new migration to the users. The migration adds a unique constraint to the "clients" table in the database. This constraint ensures that the "name" column of the "clients" table is unique.
No issue
Make username unique
Yes
No
N/A

NOISSUE - Make Username Unique

---

cmd/ws/main.go
docker/nginx/entrypoint.sh

Fixes nginx config as the alpine image doesn't have `bash` as a shell but rather `ash` or `sh`
Fixes WS adapter failing targetServerConfig
No issue
None
Tested manually
No
N/A

NOISSUE - Fix NGINX and WS

---

cli/users.go
cli/utils.go
cmd/cli/main.go
pkg/sdk/go/sdk.go
provision/service.go

Fix SDK page metadata from email to identity.
None
None
No
No

NOISSUE - Fix sdk page metadata from email to identity.

---

cli/things.go
cli/users.go
internal/api/common.go
internal/groups/api/requests.go
internal/groups/service.go
pkg/clients/clients.go
pkg/clients/postgres/clients.go
pkg/clients/status.go
pkg/sdk/go/certs_test.go
pkg/sdk/go/channels_test.go
pkg/sdk/go/consumers_test.go
pkg/sdk/go/groups_test.go
pkg/sdk/go/health_test.go
pkg/sdk/go/sdk.go
pkg/sdk/go/setup_test.go
pkg/sdk/go/things.go
pkg/sdk/go/things_test.go
pkg/sdk/go/tokens_test.go
pkg/sdk/go/users.go
pkg/sdk/go/users_test.go
things/mocks/clients.go
things/service.go
things/service_test.go
users/api/clients.go
users/mocks/clients.go
users/service.go
users/service_test.go

Fix failing tests in `sdk` package.
This relates to #37 
None
Yes
No
N/A

NOISSUE - Fix SDK Tests

---

api/openapi/things.yml
api/openapi/users.yml
pkg/clients/postgres/clients.go
pkg/sdk/go/channels.go
pkg/sdk/go/groups.go
pkg/sdk/go/sdk.go
pkg/sdk/go/things.go
things/api/logging.go
things/api/metrics.go
things/events/streams.go
things/mocks/clients.go
things/service.go
things/service_test.go
things/things.go
things/tracing/tracing.go
users/postgres/clients.go
users/service.go

Pull request title should be `MG-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/absmach/magistrala/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.
- Fix : Update user role and  Listing and retrieve users with role 
Request: 
```bash 
curl --location --request PATCH 'http://localhost/users/28cea756-f23b-408d-ab7a-43bf6f3c20cd/role' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer <TOKEN>' \
--data '{
"role": "admin"
}'
```
Response: 
```json 
{
"id": "28cea756-f23b-408d-ab7a-43bf6f3c20cd",
"credentials": {
"identity": "user1@example.com"
},
"created_at": "2023-11-23T09:03:11.411868Z",
"updated_at": …
```

NOISSUE - Fix Update user roles, Listing and retrieve users with role 

---

auth/service_test.go
bootstrap/service_test.go
certs/service_test.go
pkg/errors/repository/types.go
pkg/errors/service/types.go
things/service_test.go
twins/service.go
twins/service_test.go
users/service_test.go

Fix failing service tests in:
- bootstrap
- certs
- things
- users
https://github.com/absmach/magistrala/issues/31
None
Yes
No

NOISSUE - Fix tests

---

users/mocks/clients.go
users/postgres/clients.go
users/postgres/clients_test.go

Retrieve users by name from the database. This is a new feature. It enables the user to retrieve users by name. This is needed for search purposes
We are also retrieving the `ID` since name is not unique and email would leak sensitive information
No issue
None
Yes
No
N/A

NOISSUE - Repository Retrieve User By Name

---

internal/postgres/errors.go
invitations/postgres/invitations_test.go

This is a bug fix in `postgres.HandleError` to use magistrala errors.Wrap rather than std lib
- Updated the error assertion in the invitations_test.go file.
- Replaced the assert.ErrorIs() function with assert.True() and errors.Contains() to check if the expected error is contained in the actual error.
- Related Issue #137 
- Resolves #
Yes
No

NOISSUE - Use Magistrala `errors.Wrap` for HandleError

---

Makefile
certs/api/transport.go
pkg/events/events.go
pkg/events/nats/publisher_test.go
pkg/events/nats/setup_test.go
pkg/events/rabbitmq/publisher_test.go
pkg/events/rabbitmq/setup_test.go
pkg/events/redis/publisher_test.go
pkg/events/redis/setup_test.go
pkg/messaging/rabbitmq/setup_test.go
pkg/sdk/go/certs_test.go
pkg/sdk/go/channels_test.go
pkg/sdk/go/consumers_test.go
pkg/sdk/go/groups_test.go
pkg/sdk/go/message_test.go
pkg/sdk/go/things_test.go
pkg/sdk/go/tokens_test.go
pkg/sdk/go/users_test.go

Fixes tests in pkg
- Resolves #31

MG-31 - Fix pkg tests

---

auth/api/grpc/client.go
auth/api/grpc/endpoint.go
auth/api/grpc/endpoint_test.go
auth/api/grpc/setup_test.go
auth/api/http/keys/endpoint_test.go
auth/postgres/key_test.go
auth/service.go
auth/service_test.go

Tihis is a bug fix.
Fixes tests in auth service
- Related Issue #31 
- Resolves #
No
No

MG-31 - Fix Auth tests

---

auth/api/logging.go
bootstrap/api/logging.go
certs/api/logging.go
coap/api/logging.go
consumers/notifiers/api/logging.go
consumers/writers/api/logging.go
internal/groups/api/logging.go
invitations/middleware/logging.go
lora/api/logging.go
opcua/api/logging.go
pkg/messaging/handler/logging.go
provision/api/logging.go
readers/api/logging.go
things/api/logging.go
twins/api/logging.go
users/api/logging.go
ws/api/logging.go

This is an optimisation for Logging.
This improves Logging by updating the filtering and searchability through structured logs. 
- Related Issue #255 
No.
No.
N/A.

MG-234 - Improve Logging Middleware

---

internal/server/grpc/grpc.go

This is an update that replaces the unitary grpc interceptor method on grpc options
Replaced the gRPC server's UnaryInterceptor with StatsHandler from the otelgrpc package for enhanced monitoring capabilities, aligning with best practices for observability. This update allows us to take full advantage of OpenTelemetry's metrics and traces, thereby improving insight into our gRPC server's performance and reliability.
None
No, this does not change functionality or add new methods
No, no functionality was changed

NOISSUE - Replace deprecated instrumentation method

---

pkg/events/nats/publisher.go
pkg/events/nats/publisher_test.go
pkg/events/nats/setup_test.go
pkg/events/rabbitmq/publisher.go
pkg/events/rabbitmq/publisher_test.go
pkg/events/rabbitmq/setup_test.go
pkg/events/redis/publisher.go
pkg/events/redis/publisher_test.go
pkg/events/redis/setup_test.go
pkg/events/store/brokers_redis.go

This is a bug fix because it fixes failing tests for events package
This PR makes check interval for unpublished events configurable for redis since Redis is the only event source than that doesn't support unavailable publish i.e store events to a buffer if the server is down
No issue
No

NOISSUE - Make Check Interval Configurable

---

things/api/http/endpoints.go

This is a bug fix because it fixes the following issue: 
List Things connected to channels
```bash 
curl --location 'http://localhost/channels/26c6d4d4-5294-4484-898a-a3b7f345921a/things' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer <TOKEN>'
```
List of things connected to channel
Error Not Found
- Run Magistral with `make run`
- Create new domain and login to the newly created domain
- Create things
- Create Channels
- Connect things and channels 
- List Things connected to channel `http://localhost/channels/<channel_id>/things`
This PR adds the `AllRole` default to the role field in request (listing of things connected to a channel  request)
This required due to changes introduced related to clients roles in PR …

NOISSUE - Fix Listing of things connected to a channel 

---

pkg/messaging/handler/logging.go

This is a bug fix because it fixes the following issue: 
HTTP messages are not published into NATS 
Fix the message handle logger, which fix the HTTP message publish to NATS 
N/A
N/A

NOISSUE - Fix: messaging handler logger

---

pkg/auth/connect.go

This is a bug fix as it replaces the deprecated grpc tracing method.
Replace deprecated unary interceptor with stats handler
No issue
No change in functionality hence no tests
No since it only updates deprecated code
NA

NOISSUE - Replace deprecated gRPC metrics collection with new stats handler
