- auth/api/grpc/client.go
- auth/api/grpc/server.go
- auth/jwt/token_test.go
- auth/jwt/tokenizer.go
- auth/mocks/service.go
- bootstrap/api/endpoint_test.go
- bootstrap/events/producer/streams_test.go
- bootstrap/service.go
- bootstrap/service_test.go
- certs/service.go
- cmd/bootstrap/main.go
- cmd/certs/main.go
- cmd/smpp-notifier/main.go
- cmd/smtp-notifier/main.go
- cmd/things/main.go
- cmd/twins/main.go
- cmd/users/main.go
- consumers/notifiers/service.go
- internal/clients/grpc/auth/client.go
- internal/groups/service.go
- readers/api/endpoint.go
- readers/api/transport.go
- things/service.go
- things/standalone/standalone.go
- twins/service.go
- users/api/logging.go
- users/service.go
This pull request fixes gRPC server name to match the server package.
There is no such issue.
This fixes Things Auth API.
No.
N/A
N/A
> NOISSUE - Fix gRPC client naming

- Makefile
- Remove branch from docker project as it creates a new project whenever the branch is changed leading to a lot of cleanup.
> NOISSUE - Remove branch from docker project

- auth/api/grpc/requests.go
- auth/keys.go
- auth/service.go
Add InvitationKey to auth key types and set expiration duration
No issue
None
No
Under comments
Related to invitations service
> NOISSUE - Invitation Service Auth Helper

- auth/spicedb/policies.go
Pull request title should be `MG-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/absmach/magistrala/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.
Super Admin could not create entitles, This PR fix this bug 
Resolves #53
> MG-53 - Remove precondition check : User exists in Domain only for Super admin in add policies

- .github/workflows/ci.yaml
- .golangci.yml
- auth/api/http/domains/decode.go
- auth/api/http/domains/endpoint.go
- auth/api/http/domains/responses.go
- auth/mocks/domains.go
- auth/postgres/domains.go
- auth/service.go
- auth/service_test.go
- internal/apiutil/errors.go
- internal/groups/service.go
- things/api/http/clients.go
- things/api/http/endpoints.go
- things/api/http/requests.go
- things/service.go
- things/standalone/standalone.go
- users/api/endpoints.go
- users/service.go
Fix code formatting and remove unnecessary comments
Related to #31 
None
No
No
Added basic CI to check linting and build process as the major CI pipeline will be added during #61
> NOISSUE - Fix Linting Errors

- pkg/clients/postgres/clients_test.go
Fix failing tests on `pkg/clients` tests
Related to #37 
None
Yes
No
N/A
> NOISSUE - Fix `pkg/clients` Tests

- bootstrap/api/endpoint_test.go
- bootstrap/events/producer/events.go
- bootstrap/events/producer/streams_test.go
- bootstrap/service_test.go
Fix failing tests in the bootstrap package
This relates to #37 
None
Yes
No
N/A
> NOISSUE - Fix Bootstrap Tests

- auth/spicedb/policies.go
Signed-off-by: Arvindh <arvindh91@gmail.com>
Pull request title should be `MG-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/absmach/magistrala/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.
- Limit user to have single relation with things, groups, channels and domains
> NOISSUE: Limit user to have single relation with things, groups, channels and domains

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/PULL_REQUEST_TEMPLATE.md
This pull request updates GitHub templates for issues and pull requests.
There is no such issue.
N/A
N/A
N/A
N/A
> NOISSUE - Update GitHub templates

- go.mod
- go.sum
The commit updates the go.mod and go.sum files.
- Resolves #
> NOISSUE - Update `go.mod` and `go.sum` Files

- Makefile
- bootstrap/api/transport.go
- bootstrap/events/producer/streams_test.go
- internal/api/common.go
Makes tests in bootstrap pass
https://github.com/absmach/magistrala/issues/31
- Related Issue #31
- Resolves #
> MG-31 - Make bootstrap tests pass

- consumers/notifiers/api/endpoint_test.go
- consumers/notifiers/api/transport.go
- consumers/notifiers/service_test.go
Fix failing tests in consumer
- Related Issue #31
- Resolves #
> MG-31 - Fix Consumers tests

- .github/workflows/cd.yml
- .github/workflows/ci.yml
Prevent Tests from being Cancelled
- Resolves #90
> NOISSUE - Add failfast for CI test run

- readers/api/transport.go
Fixes failing tests in readers.
- Related Issue #31
- Resolves #
> MG-31 - Fix Readers tests

- auth/README.md
- cmd/auth/main.go
- docker/.env
- docker/docker-compose.yml
Align `auth` documentation with what is deployed
- Resolves #
To be merged after https://github.com/absmach/magistrala/pull/109
> NOISSUE - Align `auth` Documentation

- twins/api/http/endpoint_twins_test.go
- twins/api/http/transport.go
Fix failing tests in Twins service
- Related Issue #31
- Resolves #
> MG-31 - Fix Twins tests

- .github/workflows/ci.yml
This is a bug fix for WebSocket tests in ci.yml. 
This changes the error on `=coverprofile=coverage/ws.out` to `-coverprofile=coverage/ws.out`
No Issue
No
No
> NOISSUE - Fix WS Coverprofile

- .github/workflows/ci.yml
- invitations/README.md
- invitations/doc.go
- invitations/invitations.go
- invitations/invitations_test.go
This is a feature because it adds the invitation service
This PR adds the necessary data structures and methods for managing invitations to join a domain.
- Resolves #
Yes
Yes, I have added godocs
N/A
> NOISSUE - Implement Invitations Service Outline

- internal/postgres/errors.go
- invitations/invitations.go
- invitations/mocks/doc.go
- invitations/mocks/invitations.go
- invitations/postgres/doc.go
- invitations/postgres/init.go
- invitations/postgres/invitations.go
- invitations/postgres/invitations_test.go
- invitations/postgres/setup_test.go
This PR is a feature because it adds invitation service repository layer
Adds invitation service repository layer
- Resolves #
Yes, I have included tests for my changes
No, I have not updated the documentation yet. It will be done in the final PR of this feature
To be merged after https://github.com/absmach/magistrala/pull/116
> NOISSUE - Add Invitation Service Repository Layer

- auth/api/http/domains/decode.go
- auth/api/http/domains/endpoint.go
- auth/api/http/domains/requests.go
- auth/api/http/domains/responses.go
- auth/api/http/domains/transport.go
- auth/api/logging.go
- auth/api/metrics.go
- auth/domains.go
- auth/mocks/domains.go
- auth/postgres/domains.go
- auth/service.go
- auth/tracing/tracing.go
- internal/groups/postgres/groups.go
- pkg/sdk/go/domains.go
- pkg/sdk/go/sdk.go
**Add New endpoint to view domain permissions**
Example: 
Request : 
```bash
curl --location 'http://localhost/domains/3e569c55-3c94-4923-93c0-06ea00a9927a/permissions' \
--header 'Authorization: Bearer <TOKEN>'
```
Response:
```json
{
"permissions": [
"admin",
"edit",
"view",
"membership"
]
}
```
- Resolves #
>  NOISSUE - Add: View domain permissions

- Makefile
- consumers/notifiers/smpp/README.md
- consumers/notifiers/smtp/README.md
- docker/.env
- docker/addons/bootstrap/docker-compose.yml
- docker/addons/cassandra-reader/docker-compose.yml
- docker/addons/certs/docker-compose.yml
- docker/addons/influxdb-reader/docker-compose.yml
- docker/addons/mongodb-reader/docker-compose.yml
- docker/addons/postgres-reader/docker-compose.yml
- docker/addons/smpp-notifier/docker-compose.yml
- docker/addons/smtp-notifier/docker-compose.yml
- docker/addons/timescale-reader/docker-compose.yml
- docker/addons/twins/docker-compose.yml
- docker/docker-compose.yml
- docker/ssl/Makefile
- readers/cassandra/README.md
- readers/influxdb/README.md
- readers/mongodb/README.md
- readers/postgres/README.md
- readers/timescale/README.md
- things/README.md
- twins/README.md
This is a bug fix as it fixes mTLS support not working out of the box after auth changes
Make sure MTLS support works after the new auth changes
- Resolves #
I have tested the system manually
No
> NOISSUE - Fix mTLS support

- auth/spicedb/policies.go
This PR optimize spicedb checks permission and list subjects/objects 
In this PR , Full consistent is added to all check and list request to spicedb. So Now we can check thing permission as soon as it is created, No need to wait for cooling period for permission to penetrate in spicedb.
- Related Issue #140
- Resolves  #140
No, Not in this PR planned
> MG-140 - Add Full consistency for spicedb check & list gRPC requests

- auth/api/http/domains/responses.go
refactor
add's `MarshalJSON()` to retrieveDomainRes in responses.go
Before:
```
{
"Data": {
"id": "6ef148dc-114a-4e55-b771-d0ffcb5cd256",
"name": "organization 1",
"status": "enabled",
"created_by": "08c871fa-5aa8-4d32-b981-e2200c1924cb",
"created_at": "2023-12-14T09:58:27.997841Z",
"updated_at": "0001-01-01T00:00:00Z"
}
}
```
After:
```
{
"id": "6ef148dc-114a-4e55-b771-d0ffcb5cd256",
"name": "organization 1",
"status": "enabled",
"created_by": "08c871fa-5aa8-4d32-b981-e2200c1924cb",
"created_at": "2023-12-14T09:58:27.997841Z",
"updated_at": "0001-01-01T00:00:00Z"
}
```
NOISSUE
- Resolves #
NO
NO
> NOISSUE - Add JSON Marshaling to retrieveDomainRes

- tools/e2e/e2e.go
This is a bug fix as it fixes `e2e` testing tool
Fixes not working `e2e` testing tool
- Resolves #
No, I have tested manually and added it to `CD` pipeline
No, I have not documented it as it is already documented
N/A
> NOISSUE - Fix `e2e` Testing Tool

- README.md
This is a bug fix.
Fixes the push and build badges in README.
N/A
No.
No.
> NOISSUE - Update badges

- .golangci.yml
- internal/groups/mocks/groups.go
- internal/groups/postgres/groups.go
- internal/postgres/errors.go
- things/service_test.go
- twins/mongodb/twins_test.go
- users/service_test.go
This is a refactor PR because it refactors error aliases on for `repoerr` and `svcerr`
Add aliases to `golangcilint` for `repoerr` and `svcerr`
- Resolves #
No
> NOISSUE - Refactor error aliases

- things/api/http/clients.go
refactor because it changes the names of the operations affected
change the names of some operations in things service clients.go API 
noissue
- Resolves #
no
no
> NOISSUE - Fix api package operations naming

- docker/.env
This is a bug fix as it fixes formatting on env file
Fixes formatting on env file
- Resolves #
No, it is env file config
No
> NOISSUE - Fix formatting in `MG_UI_CONTENT_TYPE`

- README.md
This is a bug fix because it fixes the following issue: #174 
Updates the docker-compose command in the readme file for installing Magistrala docker services
- Resolves #174
No because if fixes a readme bug
No, because it is not a feature modification pr
> MG-174 Update install command on README.md file

- .github/workflows/tests.yml
This is an optimization because it improves the testing functionality
Splits tests under `pkg` package to separate tests. That is
- clients
- errors
- events
- groups
- messaging
- sdk
- transformers
- ulid
- uuid
- Resolves #
No, I have not included tests as it is CI test
No, I have not documented anything
> NOISSUE - Split package tests

- auth/service.go
- bootstrap/events/producer/streams_test.go
- bootstrap/service.go
- internal/postgres/errors.go
- pkg/clients/postgres/clients.go
- things/service.go
- users/service.go
This is a bug fix because it fixes the following issue: #149
Handles errors in the service layer to prevent database errors from leaking to the end user.
- Resolves #149
No,
No, since this is a bug fix.
> MG-149 - Fix leaking database errors

- auth/api/grpc/endpoint_test.go
This is a bug fix and relates to the following issue #170 
Removes a failing test which will be reimplemented in issue #170 
- Related Issue #170 
No, this is a test file change.
No.
> NOISSUE - Remove failing test in Auth

- bootstrap/api/transport.go
- certs/api/transport.go
- consumers/notifiers/api/transport.go
- internal/apiutil/token_test.go
- internal/apiutil/transport.go
- internal/apiutil/transport_test.go
- readers/api/transport.go
- twins/api/http/transport.go
This is a feature PR because it adds tests to the `apiutil` package.
The provided code includes test cases written that cover various scenarios for parsing and handling query parameters in HTTP requests. These scenarios include valid and invalid queries, empty queries, and multiple queries with the same key.
- Resolves #
No
> NOISSUE - Add Test for `apiutil` package

- .github/workflows/build.yml
- .github/workflows/tests.yml
This is an optimization as it removes some unused files that are generated.
This removes the creating of coverage.html files since codecov provides satisfactory reports.
None
No, I haven't included tests as its a CI fix.
No
> NOISSUE - Remove unused coverage.html files

- readers/api/transport.go
This is a bug fix because it fixes the reading of messages when the token if a user token.
It changes the permission from `subscribePermission` to `viewPermission` for the specified `Subject` and `Object`. This is because a group doesn't have permission to subscribe hence user can't subscribe to a group
- Resolves #
No. I have tested manually
No
This ensures both thing and user are able to read messages from a channel
> NOISSUE - Refactor auth to use `view` permission instead of `subscribe`

- auth/api/http/domains/decode.go
- auth/api/http/domains/endpoint.go
- auth/api/http/domains/requests.go
- auth/domains.go
- auth/postgres/domains.go
- auth/service.go
This is a feature because it adds the following functionality:
- Block login for non-admin users on disabled domain.
Block login for non-admin users on disabled domain.
No, Not planned in this PR
No, Not planned in this PR
> NOISSUE - Block login for non-admin users on disabled domain 

- coap/adapter.go
- http/handler.go
- mqtt/handler.go
- ws/adapter.go
- ws/handler.go
This is a refactor PR because it uses constants from the auth package rather than defining them.
- Using constants from the auth package
- Resolves #
No
> NOISSUE - Use `auth` const for Checking Authorization

- .github/dependbot.yml
This pull request is an improvement that adds an automatic dependency update to the repository.
This pull request adds support for GitHub Dependbot.
There is no such issue.
N/A
N/A
N/A
> NOISSUE - Setup Dependbot

- auth/service.go
- internal/groups/service.go
This is a bug fix because it fixes authori on groups authorization
Add domain when considering authorization for groups
- Resolves #
No, I have tested manually.
No
Before when trying to view group the error response was
```json
{"level":"warn","message":"Method view_group for group  with id  using token <jwt> took 396.396µs to complete with error: failed to perform authorization over the entity : failed to perform authorization over the domain.","ts":"2023-12-22T19:11:14.257055595Z"}
```
> NOISSUE - Fix `ListGroups` Fails to Authorize

- docker/addons/timescale-writer/docker-compose.yml
This is a feature PR because it exposes timescale to port 5433
Exposes timescale db to port 5433 to be used by other containers for example grafana
- Resolves #
Yes, I have tested manually
No, I have not updated the documentation
> NOISSUE - Expose timescale on 5433

- internal/groups/service.go
- things/service.go
- things/service_test.go
This is a feature because it adds the following functionality:
- Domains status check on Create & List of Things & Groups
Domains status check on Create & List of Things & Groups
No, No in this PR 
No, No in this PR
> NOISSUE - Domains status check on Create & List of Things & Groups

- Makefile
This is a dependency update because it updates the following dependencies:
- Makefile Uses mockery v2.38.0 to Align with GitHub Actions
Makefile Uses mockery v2.38.0 to Align with GitHub Actions
No, Not Required
No, Not Required
> NOISSUE - Makefile Uses mockery v2.38.0 to Align with GitHub Actions

- internal/groups/service.go
- things/service.go
This is a bug fix because it fixes the following issue:
- Provides fix in channels, things, groups authorization
Fix channels, things, groups authorization over domain 
No
No
> NOISSUE - Fix channels, things, groups authorization over domain 

- docker/docker-compose.yml
This is a bug fix because it fixes exposed port in spicedb which clashes with prometheus
Update docker-compose.yml to expose port 9091 instead of 9090
- Resolves #
No, I have tested manually
No
> NOISSUE - Expose Alternative Metrics Port for SpiceDB

- pkg/errors/types.go
- provision/config.go
- provision/config_test.go
This is a feature because it adds tests to the provision package.
This PR adds tests to the provision package testing the reading and saving of config files
- Resolves #
No
> NOISSUE - Add config tests

- .github/workflows/check-generated-files.yml
- .github/workflows/swagger-ui.yaml
- .github/workflows/tests.yml
- pkg/sdk/go/things_test.go
This is is a bug fix PR and also an optimization PR regarding testing on CI
- Fixes failing tests on SDK package
- Expanded filters when testing different packages based on file changes
- Resolves #
Yes, I have included tests for my changes
No, I have not updated documentation
> NOISSUE - Expand filters to check for test changes

- internal/groups/postgres/groups.go
- internal/groups/postgres/groups_test.go
- internal/groups/postgres/setup_test.go
This is a feature PR because it adds repository tests to the `groups` package
Adds repository tests to the groups package
- Resolves #
No
> NOISSUE - Add group repository tests

- provision/config.go
- provision/service.go
- provision/service_test.go
This is a feature because it adds tests to the `provision` package.
This PR adds tests to the `provision` package testing the service layer. Provision method has not been tested as it is too huge and it would need some refactoring
- Resolves #
No
To be merged after https://github.com/absmach/magistrala/pull/190
> NOISSUE - Add provision service tests

- auth/api/http/domains/decode.go
- auth/api/http/domains/endpoint.go
- auth/api/http/domains/requests.go
- auth/api/http/domains/responses.go
- auth/api/http/domains/transport.go
Adds domain freeze endpoint which allows to freeze the domain by super admin
After freezing a domain, Domain Admin and Domain users could not do any actions on domain
No, Not Planned in this PR 
No, Not planned in this PR
> NOISSUE - Add domain freeze endpoint

- cmd/mqtt/main.go
- pkg/errors/errors.go
- pkg/errors/errors_test.go
- pkg/errors/sdk_errors.go
- pkg/errors/sdk_errors_test.go
This is a refactor PR since it adds testing to `errors` package
Improve error handling and SDK error testing. Additionally, assertions have been added to ensure the expected behaviour is met.
No issue
No
> NOISSUE - Add Testing to `errors` package

- .github/workflows/tests.yml
- pkg/auth/client.go
- pkg/auth/client_test.go
- pkg/auth/connect.go
- pkg/auth/connect_test.go
This is a feature PR as it adds tests to auth package
Tests `pkg/auth` package which is used by external services
- Resolves #
No
> NOISSUE - Add test for auth package

- auth/api/http/domains/decode.go
- auth/postgres/domains.go
This is a refactor because it changes the following functionality: 
- List all status domains by default 
List all status domains by default 
- Resolves https://github.com/absmach/magistrala/issues/1968
Yes, Tested manually endpoints
No, Not planned in this PR 
Related PR in UI https://github.com/absmach/magistrala-ui/pull/65
> MG-220 - List all status domains by default

- README.md
This is a documentation update because it updates the README.
Increases the documented minimum docker-compose version to `2.20`. This is necessary because `docker/docker-compose.yml` makes use of the `include` attribute introduced in `2.20`.
- Resolves #
No, because no functional changes, documentation only.
N/A, the change is documentation
> NOISSUE - Increase minimum docker-compose version in README.md

- .github/workflows/build.yml
- .github/workflows/tests.yml
This is a CI Fix that stops the CI  from passing should any tests fail.
None.
No.
No.
> NOISSUE - Resolve falsely passing CI

- api/openapi/auth.yml
- api/openapi/users.yml
This is a documentation update because it updates the following documentation: 
- Add Domains openAPI spec 
- Add Domains openAPI spec 
- Resolves absmach/magistrala#1961 
No,  Not Applicable
No, Not Applicable
> MG-1961 - Add Domains OpenAPI Spec

- things/api/grpc/client.go
- things/api/grpc/server.go
- things/service.go
Handling of things gRPC errors in both server and client 
- Related Issue absmach/magistrala#1967 
Test partially, Websocket and HTTP doesn
No, Not related
> MG-1967 - Handle errors in Things gRPC server and client

- auth/api/grpc/server.go
- users/api/clients.go
- users/service.go
- users/service_test.go
This is a feature because it adds the following functionality: 
- While listing entity users , it added user permission to the entity in users page response. 
While listing entity users , listing  users having access to various entities like things, channels, groups, domain, 
This PR adds user permission along the Users response 
This response you can see in following endpoints by adding query parameter `list_perms=true`
`domain/{domainID}/users?list_perms=true`
`groups/{groupID}/users?list_perms=true`
`things/{thingID}/users?list_perms=true`
`channels/{channeID}/users?list_perms=true`
Example Request in Domain
```bash 
curl --location 'http://localhost/domains/6155c284-634a-475a-bbda-4a70f8a1bbee/users?list_perms=true' \
--header 'Authorization: Bearer <TOKEN>'
```
Response 
```json
{ …
```
> NOISSUE - List entity users along with permissions

- auth/postgres/domains.go
- auth/service.go
This is a bug fix because it fixes the following issue: 
- Fix list domain issue
- Fix Update Domain issue
- Fix list domain issue
- Fix Update Domain issue
> NOISSUE - Fix : List and Update Domain 

- pkg/clients/clients_test.go
- pkg/clients/page.go
- pkg/clients/postgres/clients.go
- pkg/clients/postgres/clients_test.go
- pkg/clients/roles.go
- pkg/clients/roles_test.go
- pkg/clients/status_test.go
- things/postgres/clients.go
- users/postgres/clients.go
- users/service.go
This is a feature PR because it adds repository tests to the `pkg/clients` package
Adds repository tests to the `pkg/clients` package
- Resolves #
No
> NOISSUE - Add `pkg/clients` Tests

- Makefile
- README.md
- docker/brokers/docker-compose.yml
- docker/brokers/profiles/nats.yml
This is a bug fix because it fixes docker-compose deployment to work with compose version v2.24.0
- fix compose to work with version v2.24.0
- update readme with the required versions for docker go and compose
- move from `docker-compose` to `docker compose` as it comes as a plugin in docker
- Resolves #
Yes, I have tested manually
Yes, I have updated the documentation for the new feature.
> NOISSUE - Fix Compose With v2.24.0

- cmd/twins/main.go
- coap/adapter.go
- coap/api/logging.go
- coap/api/transport.go
- consumers/notifiers/service.go
- consumers/notifiers/smpp/notifier.go
- consumers/notifiers/smtp/notifier.go
- mqtt/forwarder.go
- mqtt/handler.go
- opcua/gopcua/subscribe.go
- pkg/messaging/mqtt/pubsub_test.go
- pkg/messaging/nats/publisher.go
- pkg/messaging/nats/tracing/publisher.go
- pkg/messaging/nats/tracing/pubsub.go
- pkg/messaging/rabbitmq/publisher.go
- pkg/messaging/rabbitmq/pubsub_test.go
- pkg/messaging/rabbitmq/tracing/publisher.go
- pkg/messaging/rabbitmq/tracing/pubsub.go
- pkg/transformers/json/transformer.go
- pkg/transformers/senml/transformer.go
- tools/e2e/e2e.go
- twins/mocks/messages.go
- twins/service.go
- ws/client.go
- ws/handler.go
This is a refactor PR as it gets values from message safer
Use a safer method to extract values from the message by using `Get*` function rather than directly accessing the variables
- Resolves #
No, I have tested manually
No
> NOISSUE - Use methods for accessing in generated code

- things/api/http/endpoints.go
This is a bug fix because it fixes the listing of things
Adds `allRole` when fetching things to retrieve all things since things don't have roles.
No issue
```bash
curl -sSi -H "Authorization: Bearer $USER_TOKEN" http://localhost:9000/things
HTTP/1.1 500 Internal Server Error
Content-Type: application/json
Date: Fri, 19 Jan 2024 08:37:38 GMT
Content-Length: 107
{"error":"ERROR: column c.role does not exist (SQLSTATE 42703)","message":"failed to retrieve all groups"}
```
No tests included
Yes, I added comment regarding it
> NOISSUE - Bug Fix on Listing Things
